### ISSUE TITLE
Few Ligatures not working 

### ISSUE THREAD

**Issue by abhishekmittal15** [mtikekar/vim-bsv#3]
I have Cascadia Font PL on my windows terminal, and naturally neovim's font is also the same and hence it supports ligatures. But for some reason a few ligatures don't work in my Bluespec files like <=(register assign) and <-, their size is too small to be visible. For other file types the ligatures work fine on neovim. I think it has something to do with [syntax file](https://github.com/mtikekar/vim-bsv/blob/master/syntax/bsv.vim). But I am new to vim, so I haven't figured it out. A few more details, I am using neovim on WSL2 Ubuntu 20.04.

**Comment by mtikekar** [comment]
I would recommend just disabling the ligatures. See if `set conceallevel=0`
fixes it and you can make it permanent in init.nvim with `autocmd FileType
bsv setlocal conceallevel=0`

**Comment by abhishekmittal15** [comment]
Yes you are right, disabling ligatures would be the best way to go about it. 
```vim
syntax match bsvNiceOperator "!=" conceal cchar=≠
syntax match bsvNiceOperator "==" conceal cchar=≡
syntax match bsvNiceOperator "<-" conceal cchar=←
syntax match bsvNiceOperator "&\@<!&&&\@!" conceal cchar=∧
syntax match bsvNiceOperator "||" conceal cchar=∨
syntax match bsvNiceOperator "<<" conceal cchar=≪
syntax match bsvNiceOperator ">>" conceal cchar=≫
syntax match bsvNiceOperator ">=" conceal cchar=≥
syntax match bsvNiceOperator "<=" conceal cchar=⇐
```
Here `⇐` is not a part of my font, hence it doesnt render properly and as you said I have set the conceallevel to 0. Thanks 
Just wanted to know if the font you use render both `⇐` and `≤`. If yes, then which font is it?
